openapi: 3.0.3
info:
  title: Kanban Application V1
  description:
    <h2> User Table Schema </h2> 
      <table>
        <thead>
          <th>Column Name</th>
          <th>Column Type</th>
          <th>Constraints</th>
        </thead>
        <tbody>
          <tr>
            <td>id</td>
            <td>Integer</td>
            <td>Primary Key, Auto Increment</td>
          </tr>
          <tr>
            <td>name</td>
            <td>String</td>
            <td>Not Null, Unique</td>
          </tr>
        </tbody>
      </table>

    <h2> List Table Schema </h2> 
      <table>
        <thead>
          <th>Column Name</th>
          <th>Column Type</th>
          <th>Constraints</th>
        </thead>
        <tbody>
          <tr>
            <td>id</td>
            <td>Integer</td>
            <td>Primary Key, Auto Increment</td>
          </tr>
          <tr>
            <td>name</td>
            <td>String</td>
            <td>Not Null</td>
          </tr>
          <tr>
            <td>description</td>
            <td>String</td>
            <td></td>
          </tr>      
          <tr>
            <td>update_date</td>
            <td>String</td>
            <td>Not Null</td>
          </tr>      
          <tr>
            <td>user_id</td>
            <td>Integer</td>
            <td>Foreign Key (user.id), Not Null</td>
          </tr>         
        </tbody>
      </table>

    <h2> Card Table Schema </h2> 
      <table>
        <thead>
          <th>Column Name</th>
          <th>Column Type</th>
          <th>Constraints</th>
        </thead>
        <tbody>
          <tr>
            <td>id</td>
            <td>Integer</td>
            <td>Primary Key, Auto Increment</td>
          </tr>
          <tr>
            <td>name</td>
            <td>String</td>
            <td>Not Null</td>
          </tr>
          <tr>
            <td>content</td>
            <td>String</td>
            <td></td>
          </tr>
          <tr>
            <td>deadline</td>
            <td>String</td>
            <td>Not Null</td>
          </tr>
          <tr>
            <td>toggle</td>
            <td>String</td>
            <td>Not Null</td>
          </tr>
          <tr>
            <td>create_date</td>
            <td>String</td>
            <td>Not Null</td>
          </tr>      
          <tr>
            <td>complete_date</td>
            <td>String</td>
            <td>Not Null</td>
          </tr>      
          
          <tr>
            <td>list_id</td>
            <td>Integer</td>
            <td>Foreign Key (list.id), Not Null</td>
        </tbody>
      </table>

    <h2> Error Codes </h2> 
      <table>
        <thead>
          <th>Resource</th>
          <th>Error Code</th>
          <th>Message</th>
        </thead>
        <tbody>
          <tr>
            <td>User</td>
            <td>USER001</td>
            <td>User Id is required</td>
          </tr>
          <tr>
            <td>List</td>
            <td>LIST001</td>
            <td>List Name is required</td>
          </tr>
          <tr>
            <td>List</td>
            <td>LIST002</td>
            <td>List Name is already exists</td>
          </tr>
          <tr>
            <td>List</td>
            <td>LIST003</td>
            <td>List Id is required</td>
          </tr>          
          <tr>
            <td>Card</td>
            <td>CARD001</td>
            <td>Card Name is required</td>
          </tr>
          <tr>
            <td>Card</td>
            <td>CARD002</td>
            <td>Deadline is required</td>
          </tr>
          <tr>
            <td>Card</td>
            <td>CARD003</td>
            <td>The Date must be Bigger or Equal to today date</td>
          </tr>  
          <tr>
            <td>Card</td>
            <td>CARD004</td>
            <td>Card Name is already exists in the given list</td>
          </tr>
        </tbody>
      </table>

  version: 1.0.0
  
servers:
  - url: http://127.0.0.1:5000/
tags:
  - name: list
    description: List Management
  - name: card
    description: Card Management
paths:
  /api/lists/{user_id}:
    get:
      tags:
        - list
      summary: list of all listnames
      description: list of all listnames
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                    example: 2
                  lists:
                    type: array
                    example: [list_names]
                    
        '404':
          description: User not found
        '500':
          description: Internal Server Error
          
  /api/createlist/{user_id}:
    post:
      tags:
        - list
      summary: Create a new list
      description: Create a new list
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: list_name
                description:
                  type: string
                  example: list_description
      responses:
        '200':
          description: List created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
                  name:
                    type: string
                    example: list_name
                  description:
                    type: string
                    example: list_description
                  user_id:
                    type: integer
                    example: 1
                  
        '409':
          description: List Name already exists
        '500':
          description: Internal Server Error

  /api/deletelist/{list_id}:
    delete:
      tags:
       - list
      summary: Delete the list
      description: Delete the list
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            type: integer
            example: 2
      responses:
        '200':
          description: Successfully Deleted
        '404':
          description: List not found
        '500':
          description: Intenal Server Error
          
  /api/updatelist/{list_id}:
    put:
      tags:
        - list
      summary: Update the list
      description: Update the list
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            type: integer
            example: 2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: list_name
                description:
                  type: string
                  example: list_description
      responses:
        '200':
          description: List updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
                  name:
                    type: string
                    example: list_name
                  description:
                    type: string
                    example: list_description
                  user_id:
                    type: integer
                    example: 1
                  
        '404':
          description: List Name not exists
        '500':
          description: Internal Server Error
          
  /api/cards/{list_id}:
    get:
      tags:
        - card
      summary: list of all cardnames
      description: list of all cardnames
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  list_id:
                    type: integer
                    example: 2
                  cards:
                    type: array
                    example: [card_names]
                    
        '404':
          description: Card not found
        '500':
          description: Internal Server Error
  
  /api/createcard/{list_id}:
    post:
      tags:
        - card
      summary: Create a new card
      description: Create a new card
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: card_name
                content:
                  type: string
                  example: card_content
                deadline:
                  type: string
                  example: yyyy-mm-dd
      responses:
        '201':
          description: Card created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
                  name:
                    type: string
                    example: card_name
                  content:
                    type: string
                    example: card_content
                  deadline:
                    type: string
                    example: yyyy-mm-dd
                  toggle:
                    type: string
                    example: '0'
                  list_id:
                    type: integer
                    example: 1
        '409':
          description: Card Name already exists
        '500':
          description: Internal Server Error

  /api/deletecard/{card_id}:
    delete:
      tags:
       - card
      summary: Delete the card
      description: Delete the card
      parameters:
        - in: path
          name: card_id
          required: true
          schema:
            type: integer
            example: 2
      responses:
        '200':
          description: Successfully Deleted
        '404':
          description: Card not found
        '500':
          description: Intenal Server Error
          
  /api/updatecard/{card_id}:
    put:
      tags:
        - card
      summary: Update the card
      description: Update the card
      parameters:
        - in: path
          name: card_id
          required: true
          schema:
            type: integer
            example: 2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: card_name
                content:
                  type: string
                  example: card_content
                deadline:
                  type: string
                  example: yyyy-mm-dd
                toggle:
                  type: string
                  example: "0"
                list_id:
                  type: integer
                  example: 1
      responses:
        '200':
          description: Card updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
                  name:
                    type: string
                    example: card_name
                  content:
                    type: string
                    example: card_content
                  deadline:
                    type: string
                    example: yyyy-mm-dd
                  toggle:
                    type: string
                    example: "0"              
                  list_id:
                    type: integer
                    example: 1
                  
        '404':
          description: Card Name not exists
        '500':
          description: Internal Server Error